version: '2'

services:
 mysql:
  image: mysql:8.0.18
  environment:
      - MYSQL_ROOT_PASSWORD=grajdolex
      - MYSQL_DATABASE=tables
      - MYSQL_USER=root
      - MYSQL_PASSWORD=grajdolex
  ports:
      - 3306:3306
  volumes:
      - ./mysql:/var/lib/mysql
 app:
  build:
   context: ./
  ports:
        - 8080:8080
        - 9990:9990
  depends_on:
       - mysql
  links:
       - mysql
  dns: 8.8.8.8